### ISSUE TITLE
undefined method `*' for nil:NilClass

### ISSUE THREAD

**Issue by michaelnlindsay** [wanelo-chef/postgres#3]
Hello, just trying to use this cookbook for the first time today.  I have a very simple application cookbook that includes postress::server.  When I provision I get:
==> cake_services: ================================================================================
==> cake_services: Recipe Compile Error in /var/chef/cache/cookbooks/processor/recipes/pdf-r.rb
==> cake_services: ================================================================================
==> cake_services: 
==> cake_services: 
==> cake_services: NoMethodError
==> cake_services: -------------
==> cake_services: undefined method `*' for nil:NilClass
==> cake_services: 
==> cake_services: 
==> cake_services: Cookbook Trace:
==> cake_services: 
==> cake_services: ---------------
==> cake_services:   /var/chef/cache/cookbooks/postgres/recipes/server.rb:30:in `from_file'
==> cake_services:   /var/chef/cache/cookbooks/processor/recipes/pdf-r.rb:14:in `from_file'
==> cake_services: 
==> cake_services: 
==> cake_services: Relevant File Content:
==> cake_services: ----------------------
==> cake_services: /var/chef/cache/cookbooks/postgres/recipes/server.rb:
==> cake_services: 
==> cake_services:  23:  include_recipe 'postgres::build'
==> cake_services:  24:  
==> cake_services:  25:  case node['platform']
==> cake_services:  26:    when 'smartos'
==> cake_services:  27:      available_ram = `prtconf -m`.chomp.to_i
==> cake_services:  28:  end
==> cake_services:  29:  
==> cake_services:  30>> shared_buffers_mb       = [12000, (available_ram * 0.25).to_i].min
==> cake_services:  31:  effective_cache_size_mb = (available_ram * 0.95).to_i - shared_buffers_mb
==> cake_services:  32:  
==> cake_services:  33:  node.default['postgres']['config']['shared_buffers_mb']       = shared_buffers_mb
==> cake_services:  34:  node.default['postgres']['config']['effective_cache_size_mb'] = effective_cache_size_mb
==> cake_services:  35:  
==> cake_services:  36:  version       = node['postgres']['version']                # eg 9.2.1
==> cake_services:  37:  version_abbr  = version.split('.').slice(0..1).join        # eg 92
==> cake_services:  38:  version_num   = version.split('.').join                    # eg 921
==> cake_services:  39:  

I even tried adding default["platform"] = "smartos" to my attributes, no luck.

TIA,
 -Michael

**Comment by kigster** [comment]
You should try running on your system the command that cookbook is running:
```prtconf -m```
If this command fails on your system, the `available_ram` variable will not be set, and you'll get this behavior.  If you are installing this on an operating system other than SmartOS you probably want to add another system to the `case` statement, and use your native OS tools to find out available ram.

For example on a Linux system where command `free` command is available you can use the following command:

```bash
free_bytes=`free | grep Mem | awk '{print $2}'`; available_ram=$(($free_bytes / 1024)); 
```
Hope this helps.

**Comment by kigster** [comment]
I patched the cookbook, please try this fork:

https://github.com/kigster/postgres
