### ISSUE TITLE
ipaddr_extensions dependency failing

### ISSUE THREAD

**Issue by michaelnlindsay** [wanelo-chef/postgres#5]
Hello, I'm using your extension to install postgres on Ubuntu 10.4.  In most circumstances this works fine for us, but when I first attempt to run it as it is booting up, I get error you see below.  If I ssh there afterward (and patch everything up because it didn't save the run_list for the node) and run chef-client again, it's fine.  Any idea what might be causing this?  

TIA, 
 -Michael

================================================================================
Recipe Compile Error in /var/chef/cache/cookbooks/ipaddr_extensions/libraries/gem_installation.rb
================================================================================

LoadError
---------
cannot load such file -- ipaddr_extensions

Cookbook Trace:
---------------
  /var/chef/cache/cookbooks/ipaddr_extensions/libraries/gem_installation.rb:2:in `<top (required)>'

Relevant File Content:
----------------------
/var/chef/cache/cookbooks/ipaddr_extensions/libraries/gem_installation.rb:

  1:  begin
  2>>   require 'ipaddr_extensions'
  3:  rescue LoadError
  4:    if Gem.respond_to?(:install)
  5:      Gem.install 'ipaddr_extensions'
  6:    else
  7:      require 'rubygems/commands/install_command'
  8:      cmd = Gem::Commands::InstallCommand.new
  9:      cmd.handle_options %w(--no-ri --no-rdoc ipaddr_extensions)
 10:
 11:      begin

**Comment by sax** [comment]
What version of ruby and rubygems are you using? Also, what version of Chef are you using?

I have a test-kitchen suite in the ipaddr_extensions cookbook, but have not run them in a very long time. https://github.com/livinginthepast/ipaddr_extensions

**Comment by sax** [comment]
I just pushed a new version of the ipaddr_extensions cookbook that works around this issue.
