### ISSUE TITLE
'postgres::server' recipe is not including the 'smf' cookbook

### ISSUE THREAD

**Issue by mcamou** [wanelo-chef/postgres#6]
When running a recipe that includes the `postgres::server` recipe, you get the following error:

```
       [2015-07-29T15:50:12+00:00] ERROR: smf[postgres944] (postgres::server line 133) had an error: NameError: uninitialized constant Builder
```

This is solved by doing an `include_recipe 'smf'` before including `postgres::server`. The `postgres::server` recipe should do the include itself.

/cc @bixu

**Comment by sax** [comment]
Sorry this took so long to get to. I've just pushed a new version that includes `smf`.

**Comment by bixu** [comment]
:tada:
