### ISSUE TITLE
Possible to update to berkshelf?

### ISSUE THREAD

**Issue by fire** [wanelo-chef/postgres#7]
It would benefit maintainability if the recipe was upgrade to berkshelf.

**Comment by sax** [comment]
Is there anything needed other than an update to the Gemfile and an addition of a Berksfile?

Just for my own knowledge, is there anything incompatible now? I use Berkshelf with test-kitchen, but our main chef repo uses Librarian.

**Comment by sax** [comment]
I've just pushed a new version that includes berkshelf. Let me know if you run into issues, and I'll reopen this issue.
